export default LANGUAGES = [
    [27, "Python 3", "py", "py3"]
    [1, "Free Pascal 3", "pas"]
    [30, "PascalABC 3"]
    [3, "GNU C++", "cpp"]
    [2, "GNU C"]
    [8, "Borland Delphi"]
    [18, "Java JDK", "java"]
    [22, "PHP", "php"]
    [23, "Python 2"]
    [24, "Perl", "pl"]
    [25, "Mono C#", "cs"]
    [26, "Ruby"]
    [28, "Haskell GHC"]
    [29, "FreeBASIC", "bas"]
    [68, "GNU C++ / sanitizer"]
]

